SELECT sos.ID, sos.OWNER_ID, sos.CREATED_BY_ID, sos.CREATED_DATE, sus.NAME, usr_role.name
FROM
CLEANSED.SALESFORCE.SALESFORCE_OPPORTUNITY_SCD2 sos
LEFT JOIN CLEANSED.SALESFORCE.SALESFORCE_USER_SCD2 sus
    ON sos.OWNER_ID = sus.ID
    --AND sus.VALID_TO_TIMESTAMP = '9999-12-31'
    AND DATE(sos.created_date) BETWEEN sus.VALID_FROM_TIMESTAMP AND sus.VALID_TO_TIMESTAMP
LEFT JOIN CLEANSED.SALESFORCE.SALESFORCE_USER_ROLE_SCD2 usr_role
    ON sus.USER_ROLE_ID = usr_role.ID
    AND DATE(sus.created_date) BETWEEN usr_role.VALID_FROM_TIMESTAMP AND usr_role.VALID_TO_TIMESTAMP
    --AND usr_role.VALID_TO_TIMESTAMP = '9999-12-31'

WHERE 1=1
  AND sos.STAGE_NAME NOT IN ('00 - Prospect & Plan', '01 - Qualify Need', 'Omitted')
  AND sos.CAMPAIGN_ID LIKE '%70180000001JlouAAC%'
  AND sos.VALID_TO_TIMESTAMP = '9999-12-31'
  AND sos.CREATED_DATE >= '2025-07-01'
  AND sos.CREATED_DATE < '2026-01-01'
  AND sus.ID = '0051E00000FjbrUQAR'
  --AND a.PRO_FORMA_MARKET_SEGMENT = 'Digital'
